src/Entity/Books.php
<?php

namespace App\Entity;

use App\Entity\Loans;
use App\Enum\BookCondition;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\BooksRepository;
use phpDocumentor\Reflection\Types\Self_;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: BooksRepository::class)]
class Books
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 510)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $Author = null;

    #[ORM\Column(length: 255)]
    private ?string $ISBN = null;

    #[ORM\Column(length: 255)]
    private ?string $bookCondition;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $summary = null;

    #[ORM\Column(nullable: true)]
    private ?bool $reserved = null;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'book')]
    private Collection $comment;
    
    /**
     * @var Collection<int, Loans>
     */
    #[ORM\OneToMany(targetEntity: Loans::class, mappedBy: 'book')]
    private Collection $loans;


    #[ORM\Column(length: 4)]
    private ?string $releaseDate = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;
    
    public function __construct()
    {   
        $this->loans = new ArrayCollection();
        $this->comment = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): static
    {
        $this->Author = $Author;

        return $this;
    }

    public function getISBN(): ?string
    {
        return $this->ISBN;
    }

    public function setISBN(string $ISBN): static
    {
        $this->ISBN = $ISBN;

        return $this;
    }

    public function getBookCondition(): ?string
    {
        return $this->bookCondition;
    }

    public function setBookCondition(String $bookCondition): Self
    {
        $this->bookCondition = $bookCondition;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): static
    {
        $this->summary = $summary;

        return $this;
    }

    public function isReserved(): ?bool
    {
        return $this->reserved;
    }

    public function setReserved(?bool $reserved): static
    {
        $this->reserved = $reserved;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comment->contains($comment)) {
            $this->comment->add($comment);
            $comment->setBook($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getBook() === $this) {
                $comment->setBook(null);
            }
        }

        return $this;
    }
    
    /**
     * @return Collection<int, Loans>
     */
    public function getLoan(): Collection
    {
        return $this->loan;
    }

    public function addLoan(Loans $loan): static
    {
        if (!$this->loan->contains($loan)) {
            $this->loan->add($loan);
            $loan->setBook($this);
        }

        return $this;
    }

    public function removeLoan(Loans $loan): static
    {
        if ($this->loan->removeElement($loan)) {

            if ($loan->getBook() === $this) {
                $loan->setBook(null);
            }
        }

        return $this;
    }

    public function getReleaseDate(): ?string
    {
        return $this->releaseDate;
    }

    public function setReleaseDate(string $releaseDate): static
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use App\Enum\UserRole;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;


class UsersType extends AbstractType
{

    private $authorizationChecker;

    public function __construct(AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstName', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'prenom cannot be empty'
                    ]),
                ],
            ])
            ->add('lastName', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'nom cannot be empty'
                    ]),
                ],
            ])
            ->add('birthday', BirthdayType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'ddn cannot be empty'
                    ]),
                ],
            ])
            ->add('address', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'address cannot be empty'
                    ]),
                ],
            ])
            ->add('postalCode', TextType::class, [])
            ->add('ville', TextType::class, [])
            ->add('telephone', TextType::class, [])
            ->add('email', EmailType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'email cannot be empty'
                    ]),
                ],
            ]);
            if ($this->authorizationChecker->isGranted('ROLE_USER')) {
            $builder->add('plainPassword', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ]);
            }
            $builder->add('subscriptionType', ChoiceType::class, [
                'choices'  => [
                    'Annually (10% Discount 287.88€)' => 'annual',
                    'Monthly (23.99€)' => 'monthly',
                ],
                'label' => 'Subscription Type',
                'mapped' => false,
            ]);
        if (!$options['is_authenticated']) {
            $builder->add('agreeTerms', CheckboxType::class, [
                'mapped' => false,
                'constraints' => [
                    new IsTrue([
                        'message' => 'You should agree to our terms.',
                    ]),
                ],
            ]);
        }
        if ($this->authorizationChecker->isGranted('ROLE_ADMIN')) {
            $builder->add('roles', ChoiceType::class, [
                'choices' => [
                    'User' => UserRole::USER->value,
                    'Admin' => UserRole::ADMIN->value,
                    'Ban User' => UserRole::BANNED->value,
                ],
                'mapped' => false,
                'expanded' => true,
                'multiple' => false,
                'label' => 'Role',
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
            'is_authenticated' => true,
        ]);
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Enum\UserRole;
use App\Form\UsersType;
use App\Entity\Abonnement;
use App\Repository\LoansRepository;
use App\Repository\ReservationsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;


//////////// All users (list)
#[Route('/users')]
final class UsersController extends AbstractController
{
    /////////// ADD user (register)
    #[Route('/register', name: 'app_users_register', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('index_books');
        }

        $user = new Users();
        $abonnement = new Abonnement();
        $form = $this->createForm(UsersType::class, $user, [
            'is_authenticated' => $this->getUser() !== null,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var string $plainPassword */
            $plainPassword = $form->get('plainPassword')->getData();

            // encode the plain password
            $user->setPassword($userPasswordHasher->hashPassword($user, $plainPassword));

            $chosenAbonnement = $form->get('subscriptionType')->getData();
            $abonnement->setSubscriptionType($chosenAbonnement);

            $monthlyCost = 23.99;
            if ($chosenAbonnement === 'annual') {
                $abonnement->setPrice($monthlyCost * 12);
                $renewalDate = new \DateTime();
                $renewalDate->modify('+12 months');
                $abonnement->setRenewal($renewalDate);
            } else {
                $abonnement->setPrice($monthlyCost);
                $renewalDate = new \DateTime();
                $renewalDate->modify('+1 months');
                $abonnement->setRenewal($renewalDate);            
            }
            
            $entityManager->persist($abonnement);
            $user->setAbonnement($abonnement);  // to inject data to abonnement table through user table \\
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('index_books');
            // return $this->redirectToRoute('app_users_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('users/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /////////////////// user dashboard 
    #[Route('/profile', name: 'app_users_show', methods: ['GET'])]
    public function show(LoansRepository $loansRepository, ReservationsRepository $resevationsRepository): Response
    {
        $user = $this->getUser();
        if (!$user) {
            throw $this->createAccessDeniedException('You must be logged in to access this page.');
        }

        $loans = $loansRepository->findByUser($user);
        $reservations = $resevationsRepository->findByUser($user);

        return $this->render('users/show.html.twig', [
            'user' => $user,
            'loans' => $loans,
            'reservations' => $reservations,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_users_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Users $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $userRoleEnum = UserRole::from($form->get('roles')->getData());
            $user->setRoles($userRoleEnum);
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_users_show');
        }

        return $this->render('users/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_users_delete', methods: ['POST'])]
    public function delete(Request $request, Users $user, EntityManagerInterface $entityManager): Response
    {
        // if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->getPayload()->getString('_token'))) {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/users/_comment_list.html.twig
<section class="dashboard-details">
  <div class="details-section">
    <h2>User Comments</h2>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Rating</th>
          <th>Comments</th>
        </tr>
      </thead>
      <tbody>
        {% for showComment in showComments %}
        <tr>
          <td>
            {{ showComment.user.firstName ~ ' ' ~ showComment.user.lastName }}
          </td>
          <td>
            <div
              class="starability-result"
              data-rating="{{ showComment.rating }}"
            ></div>
          </td>
          <td>{{ showComment.comment }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>

templates/users/_comment_user.html.twig
{# , { 'attr': {'class': 'form-comment-container'} } #}

<div class="form-comment-container">
  {{ form_start(form) }}
  <legend>Rate This Book</legend>
      {{ form_label(form.rating, 'Rate This Book') }}
      {{ form_widget(form.rating) }}

      <div class="comments">
        <label>Leave Your Comment</label>
        {{ form_widget(form.comment) }}
      </div>
      <button type="submit" class="submit btn">Submit</button>
  
  {{ form_end(form) }}
</div>

templates/users/_delete_form.html.twig
<form method="post" action="{{ path('app_users_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="delete btn" type="submit">Delete</button>
</form>

templates/users/_form.html.twig
<div class="container register-container">
  <div class="custom-progress-bar">
    <div class="step active">
      <p>Personal Info</p>
      <div class="bullet"><span>1</span></div>
      <div class="check fa-solid fa-check"></div>
    </div>
    <div class="step">
      <p>Contact</p>
      <div class="bullet"><span>2</span></div>
      <div class="check fa-solid fa-check"></div>
    </div>
    <div class="step">
      <p>Birth</p>
      <div class="bullet"><span>3</span></div>
      <div class="check fa-solid fa-check"></div>
    </div>
    <div class="step">
      <p>Address</p>
      <div class="bullet"><span>4</span></div>
      <div class="check fa-solid fa-check"></div>
    </div>
    <div class="step">
      <p>Submit</p>
      <div class="bullet"><span>5</span></div>
      <div class="check fa-solid fa-check"></div>
    </div>
  </div>

  <div class="form-outer">
      <div class="page slide-page active">
        <div class="title">Basic Info:</div>
        <div class="form-group">
          {{ form_label(form.firstName) }}
          {{ form_widget(form.firstName, { attr: { class: "form-control" } }) }}
        </div>
        <div class="form-group">
          {{ form_label(form.lastName) }}
          {{ form_widget(form.lastName, { attr: { class: "form-control" } }) }}
        </div>
        <div class="title">Date of Birth:</div>
        <div class="form-group">
          {{ form_label(form.birthday) }}
          <div class="form-inline">
            {{
              form_widget(form.birthday, {
                attr: { class: "datepicker" }
              })
            }}
          </div>
        </div>
        <div class="field">
          <button class="firstNext next btn">Next</button>
        </div>
      </div>
      <div class="page">
        <div class="title">Contact Info:</div>
        <div class="form-group">
          {{ form_label(form.email) }}
          {{ form_widget(form.email, { attr: { class: "form-control" } }) }}
        </div>
        <div class="form-group">
          {{ form_label(form.telephone) }}
          {{ form_widget(form.telephone, { attr: { class: "form-control" } }) }}
        </div>
        <div class="field btns">
          <button class="prev-1 prev btn">Previous</button>
          <button class="next-1 next btn">Next</button>
        </div>
      </div>
      <div class="page">
        <div class="form-group">
          {{ form_label(form.address) }}
          {{ form_widget(form.address, { attr: { class: "form-control" } }) }}
        </div>
        <div class="form-group">
          {{ form_label(form.ville) }}
          {{ form_widget(form.ville, { attr: { class: "form-control" } }) }}
        </div>
        <div class="form-group">
          {{ form_label(form.postalCode) }}
          {{ form_widget(form.postalCode, { attr: { class: "form-control" } }) }}
        </div>
        <div class="field btns">
          <button class="prev-2 prev btn">Previous</button>
          <button class="next-2 next btn">Next</button>
        </div>
      </div>
      <div class="page">
        <div class="title">Login Details:</div>
        <div class="form-group">
          {{ form_label(form.plainPassword) }}
          {{
            form_widget(form.plainPassword, { attr: { class: "form-control" } })
          }}
        </div>
        <div class="form-group">
          {{ form_label(form.subscriptionType) }}
          {{
            form_widget(form.subscriptionType, {
              attr: { class: "form-control" }
            })
          }}
        </div>
        <div class="form-group checkmark">
          {{ form_label(form.agreeTerms) }}
          {{ form_widget(form.agreeTerms) }}
        </div>
        <div class="field btns">
          <button class="prev-3 prev btn">Previous</button>
          <button type="submit" class="submit btn">Submit</button>
        </div>
      </div>
  </div>
</div>

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Users{% endblock %}

{% block body %}
    <h1>Edit Users</h1>

    <div class="form-container">
    {{ form_start(form) }}
        <div class="row g-3">
            <div class="col-md-6">
                {{ form_label(form.firstName, 'First Name', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.firstName, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.firstName) }}
            </div>
            <div class="col-md-6">
                {{ form_label(form.lastName, 'Last Name', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.lastName, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.lastName) }}
            </div>
            <div class="col-md-6">
                {{ form_label(form.birthday, 'Birthday', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.birthday, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.birthday) }}
            </div>
            <div class="col-md-6">
                {{ form_label(form.telephone, 'Phone', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.telephone, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.telephone) }}
            </div>
            <div class="col-md-6">
                {{ form_label(form.address, 'Address', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.address, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.address) }}
            </div>
            <div class="col-md-4">
                {{ form_label(form.ville, 'City', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.ville, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.ville) }}
            </div>
            <div class="col-md-2">
                {{ form_label(form.postalCode, 'Postal Code', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.postalCode, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.postalCode) }}
            </div>
            <div class="col-md-6">
                {{ form_label(form.email, 'Email', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.email) }}
            </div>
            {% if is_granted('ROLE_USER') %}
            <div class="col-md-6">
                {{ form_label(form.plainPassword, 'Password', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.plainPassword, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.plainPassword) }}
            </div>
            {% endif %}
            <div class="col-md-6">
                {{ form_label(form.subscriptionType, 'Subscription Type', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.subscriptionType, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.subscriptionType) }}
            </div>
            {% if is_granted('ROLE_ADMIN') %}
            <div class="col-md-6">
                {{ form_label(form.roles, 'Role', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.roles, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.roles) }}
            {% endif %}
            <span>
                <a class="back btn" href="{{ app.request.headers.get('referer') ?? '#' }}">Back</a>
                <button type="submit" class="edit btn">{{ button_label|default('Update') }}</button>
                {{ include('users/_delete_form.html.twig') }}
            </span>
            {{ form_end(form) }}
        </div>
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users index{% endblock %}

{% block body %}
    <h1>Admin Panel</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>FirstName</th>
                <th>LastName</th>
                <th>Address</th>
                <th>PostalCode</th>
                <th>Ville</th>
                <th>Telephone</th>
                <th>Birthday</th>
                <th>Email</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.address }}</td>
                <td>{{ user.postalCode }}</td>
                <td>{{ user.ville }}</td>
                <td>{{ user.telephone }}</td>
                <td>{{ user.birthday ? user.birthday|date('d-m-Y') : '' }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <a class="back btn" href="{{ path('app_users_show', {'id': user.id}) }}">show</a>
                    <a class="edit btn" href="{{ path('app_users_edit', {'id': user.id}) }}">edit</a>
                    <a class="logout btn" href="{{ path('comment_by_user', {'id': user.id}) }}">comment</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="edit btn" href="{{ path('admin_register_user') }}">Create New User</a>
    <a class="logout btn" href="{{ path('comment_list') }}">See All Comments</a>

{% endblock %}

templates/users/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}


{% block body %}
    <h1>Register</h1>
    {{ form_start(form) }}
   {{ include('users/_form.html.twig') }} 
   {{ form_end(form) }}
   <script src="{{ asset('app.js') }}"></script>
{% endblock %}

templates/users/show.html.twig
{% extends 'base.html.twig' %} {% block body %}
<div class="dashboard-container">
  <header class="dashboard-header">
    <h1>Welcome, {{ user.firstName }}</h1>
    <p>Here’s an overview of your account and activities.</p>
  </header>

  <section class="dashboard-summary">
    <div class="card">
      <h2>Borrowed Books</h2>
      <p>{{ loans | length }}</p>
    </div>
    <div class="card">
      <h2>Reserved Rooms</h2>
      <p>{{ reservations | length }}</p>
    </div>
    <div class="card">
      <h2>Total Fines</h2>
      <p>€{{ fines|default(0) }}</p>
    </div>
  </section>

  <section class="dashboard-details">
    <div class="details-section">
      <h2>Borrowed Books</h2>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Borrow Date</th>
            <th>Due Date</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {% for loan in loans %}
          <tr>
            <td>{{ loan.book.title }}</td>
            <td>{{ loan.book.author }}</td>
            <td>{{ loan.borrowDate|date('Y-m-d') }}</td>
            <td>{{ loan.dueDate|date('Y-m-d') }}</td>
            <td>{{ loan.returned ? "Returned" : "Borrowed" }}</td>
          </tr>
          {% else %}
          <tr>
            <td colspan="5">No books borrowed.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="details-section">
      <h2>Reserved Rooms</h2>
      <table>
        <thead>
          <tr>
            <th>Room Name</th>
            <th>Start Date</th>
            <th>End Date</th>
          </tr>
        </thead>
        <tbody>
          {% for reservation in reservations %}
          <tr>
            <td>{{ reservation.salle.nom }}</td>
            <td>{{ reservation.startDate|date('Y-m-d') }}</td>
            <td>{{ reservation.endDate|date('Y-m-d') }}</td>
          </tr>
          {% else %}
          <tr>
            <td colspan="3">No reserved rooms.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>

  <div class="action-buttons">
    <div class="btn-left">
      <a class="back btn" href="{{ app.request.headers.get('referer') ?? '#' }}">Back</a>
    </div>
    <div class="btn-right">
      <a href="{{ path('app_users_edit', { id: user.id }) }}" class="btn edit">Edit</a>
      {{ include("users/_delete_form.html.twig") }}
      <a href="{{ path('app_logout') }}" class="btn logout">Logout</a>
    </div>
  </div>

  {% endblock %}